[package]
name = "eymo"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
candle-core = "0.9.1"
candle-onnx = "0.9.1"
ndarray = "0.16.1"
opencv = "0.94.4"
ort = { version = "=2.0.0-rc.9", features = ["ndarray"] }
