[package]
name = "eymo-wasm"
version = "0.1.0"
edition = "2024"
features = [ "test" ]

[features]
debug = ["console_error_panic_hook"]

[dependencies]
console_error_panic_hook = { version = "0.1.7", optional = true }
wasm-bindgen = { version = "0.2.84", optional = true }

[lib]
crate-type = ["cdylib"]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
